### ISSUE TITLE
logout not working when display errors is on

### ISSUE THREAD

**Issue by si4dev** [atk4/atk4#448] opened 2013-10-21 11:22 UTC
page=logout generates pathfinder error and reports this error on screen and due to this headers cannot be changes so session is not changed  and cannot log out the user.

**Comment by DarkSide666** [comment] 2016-02-17 17:32
Can not reproduce and looks like fixed in https://github.com/wrheeder/atk4/commit/b329d14baf19d8d85745dca22eb5eba0cb97b6ae

**Closed by DarkSide666** 2016-02-17 17:32 UTC
Labels: for add-on
